#!/bin/bash
#
# Perform necessary test setup steps after package is installed.
#

PROGNAME=$(basename $0)

error_exit()
{
  echo "${PROGNAME}: ${1:-"Unknown Error"}" 1>&2
  exit 1
}

# Create fastify service user
id -u fastify >/dev/null 2>&1 || \
  useradd -r -d /opt/test -s /sbin/nologin \
    -c "fastify service account" fastify

chown -R "fastify:fastify" /opt/test/server/frontend-build/scripts /opt/test/server/frontend-build/public/data /opt/test/server/frontend-build/.next /opt/test/server/standalone-entrypoint.sh
chmod -R 555 /opt/test/server/frontend-build/scripts  /opt/test/server/standalone-entrypoint.sh
chmod -R 755 /opt/test/server/frontend-build/.next

chmod +x /opt/test/bin/node /opt/test/bin/npm /opt/test/bin/npx

chown -R fastify /etc/ssl/certs
chown fastify /etc/ssl/certs/ca-certificates.crt
chmod -R u+rwx /etc/ssl/certs
chmod u+rw /etc/ssl/certs/ca-certificates.crt
chown fastify /usr/sbin/update-ca-certificates
chmod u+rx /usr/sbin/update-ca-certificates


# Create systemd service file
cat > /etc/systemd/system/test.service <<EOF
[Unit]
Description=Fastify Server
After=network.target

[Service]
Type=simple
User=fastify
Group=fastify
WorkingDirectory=/opt/test/server
Environment=NODE_ENV=production
Environment="PATH=$PATH:/opt/test/bin"
EnvironmentFile=/etc/test/infisical.env
ExecStart=/opt/test/server/standalone-entrypoint.sh
Restart=always
RestartSec=10

[Install]
WantedBy=multi-user.target
EOF

# Reload systemd and enable service
systemctl daemon-reload
# This should triggered by the ctl commands
systemctl enable test
systemctl start test

exit 0