name 'infisical'
maintainer 'infisical.com'
maintainer_email 'support@infisical.com'
license 'Apache 2.0'
description 'Install and configure Infisical from Omnibus'
long_description 'Install and configure Infisical from Omnibus'
version '0.0.1'
recipe 'infisical', 'Configures Infisical from Omnibus'

supports 'ubuntu'

depends 'package'
# depends 'logrotate'
# depends 'postgresql'
# depends 'redis'
# depends 'monitoring'
# depends 'registry'
# depends 'mattermost'
# depends 'consul'
# depends 'gitaly'
# depends 'praefect'
# depends 'infisical-kas'
# depends 'infisical-pages'
# depends 'letsencrypt'
# depends 'nginx'
