#!/bin/sh
# WARNING: REQUIRES /bin/sh
#
# - must run on /bin/sh on Solaris 9
# - must run on /bin/sh on AIX 6.x
# - if you think you are a bash wizard, you probably do not understand
#   this programming language. Do not touch.
# - if you are under 40, get peer review from your elders.
# - akhilmhdh: Sorry, everyone is under 40 now. T-T

is_smartos() {
  uname -v | grep "^joyent" >/dev/null 2>&1
}

if is_smartos; then
  PREFIX="/opt/local"
else
  PREFIX="/usr"
fi

cleanup_symlinks() {
  # binaries="gitlab-ctl gitlab-psql gitlab-backup"
  binaries="infisical-ctl"
  for binary in $binaries; do
    rm -f "$PREFIX/bin/$binary"
  done
}

# Clean up binary symlinks if they exist
# see: http://tickets.opscode.com/browse/CHEF-3022

if [ ! -f /etc/redhat-release ] && [ ! -f /etc/fedora-release ] && [ ! -f /etc/system-release ]; then
  # not a RedHat-ish RPM-based system
  cleanup_symlinks
elif [ "x$1" = "x0" ]; then
  # RPM-based system and we're deinstalling rather than upgrading
  cleanup_symlinks
fi