#!/bin/bash
#
# Perform necessary infisical setup steps after package is installed.
#

PROGNAME=$(basename $0)

error_exit()
{
  echo "${PROGNAME}: ${1:-"Unknown Error"}" 1>&2
  exit 1
}

/opt/infisical-core/embedded/bin/symlink_ctl_cmds

exit 0